### ISSUE TITLE
Questions about transactionparser

### ISSUE THREAD

**Issue by rcamino** [ripple/ripple-lib-extensions#32]
Hello!

I've been fetching some transactions from Ripple:
https://ripple.com/build/data-api-v2/#get-transactions

I want to use this data for academic research, but I have a lot of questions about how to interpret the affected nodes. I've found some information in the API:

https://ripple.com/build/transactions/#transaction-results

in this official blog post:

https://ripple.com/dev-blog/calculating-balance-changes-for-transaction/#

and also looking at your code:

https://github.com/ripple/ripple-lib-extensions/blob/master/transactionparser/src/orderbookchanges.js

Where can I find more information?
For example, where did you get the information in this comment:

https://github.com/ripple/ripple-lib-extensions/blob/master/transactionparser/src/orderbookchanges.js#L71

Thank you very much.
Ramiro.

**Comment by clark800** [comment]
The best reference is probably ripple.com/build, though it may be missing some information you might need for advanced use cases. For those cases you can read the source code of https://github.com/ripple/ripple-lib (and it's dependencies), or https://github.com/ripple/rippled or ask a question on https://forum.ripple.com/.
